# Generated by Django 5.1.5 on 2026-01-03 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='current_session_token',
            field=models.CharField(blank=True, help_text='Current active JWT token JTI', max_length=500, null=True),
        ),
    ]
