# Generated by Django 5.2 on 2025-04-15 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appversion',
            options={'ordering': ['-created_at'], 'verbose_name': 'App Version', 'verbose_name_plural': 'App Versions'},
        ),
    ]
