# Generated by Django 5.2 on 2025-05-10 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_appversion_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sliderimage',
            options={'ordering': ['-created_at']},
        ),
    ]
