# Generated by Django 5.1.5 on 2026-03-14 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('core', '0002_initial'),
        ('courses', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appversion',
            name='force_update',
            field=models.BooleanField(default=False, help_text='User ko bina update kiye app chalane se rokna hai?'),
        ),
        migrations.AlterField(
            model_name='sliderimage',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sliders', to='categories.category'),
        ),
        migrations.AlterField(
            model_name='sliderimage',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sliders', to='courses.course'),
        ),
        migrations.AlterField(
            model_name='sliderimage',
            name='show_from',
            field=models.DateTimeField(help_text='Banner kab se dikhana shuru karna hai'),
        ),
        migrations.AlterField(
            model_name='sliderimage',
            name='show_until',
            field=models.DateTimeField(blank=True, help_text='Banner kab hatana hai (Khali chhodne par hamesha dikhega)', null=True),
        ),
    ]
