# Generated by Django 5.1.5 on 2026-03-18 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_appversion_force_update_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appversion',
            name='force_update',
            field=models.BooleanField(default=False, help_text='Block app usage until user updates'),
        ),
        migrations.AlterField(
            model_name='sliderimage',
            name='show_from',
            field=models.DateTimeField(help_text='When to start showing this banner'),
        ),
        migrations.AlterField(
            model_name='sliderimage',
            name='show_until',
            field=models.DateTimeField(blank=True, help_text='When to stop showing (null = always visible)', null=True),
        ),
    ]
