# Generated by Django 5.1.5 on 2026-01-19 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chapters', '0001_initial'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='courses.course'),
        ),
        migrations.AddField(
            model_name='chaptersection',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapter_sections', to='chapters.chapter'),
        ),
        migrations.AddField(
            model_name='chaptersection',
            name='section',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chapter_section', to='courses.section'),
        ),
        migrations.AlterUniqueTogether(
            name='chaptersection',
            unique_together={('chapter', 'section')},
        ),
    ]
