# Generated by Django 5.1.5 on 2025-12-17 15:58

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0004_add_video_file_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Template name', max_length=200)),
                ('title', models.CharField(help_text='Certificate title', max_length=300)),
                ('subtitle', models.CharField(blank=True, help_text='Certificate subtitle', max_length=300)),
                ('header_text', models.TextField(blank=True, help_text='Header text above recipient name')),
                ('body_text', models.TextField(blank=True, help_text='Main body text')),
                ('footer_text', models.TextField(blank=True, help_text='Footer text')),
                ('background_image', models.ImageField(blank=True, help_text='Background image for certificate', null=True, upload_to='certificate_templates/')),
                ('primary_color', models.CharField(default='#2C3E50', help_text='Primary color (hex code)', max_length=7)),
                ('secondary_color', models.CharField(default='#3498DB', help_text='Secondary color (hex code)', max_length=7)),
                ('font_family', models.CharField(default='Arial, sans-serif', help_text='Font family', max_length=100)),
                ('font_size_title', models.IntegerField(default=48, help_text='Title font size (px)', validators=[django.core.validators.MinValueValidator(12), django.core.validators.MaxValueValidator(72)])),
                ('font_size_body', models.IntegerField(default=24, help_text='Body font size (px)', validators=[django.core.validators.MinValueValidator(8), django.core.validators.MaxValueValidator(48)])),
                ('organization_name', models.CharField(default='E-Learning Platform', help_text='Organization/Platform name', max_length=200)),
                ('organization_logo', models.ImageField(blank=True, help_text='Organization logo', null=True, upload_to='certificate_logos/')),
                ('signature_1_title', models.CharField(blank=True, help_text="First signature title (e.g., 'Director')", max_length=100)),
                ('signature_1_name', models.CharField(blank=True, help_text='First signature name', max_length=100)),
                ('signature_1_image', models.ImageField(blank=True, help_text='First signature image', null=True, upload_to='certificate_signatures/')),
                ('signature_2_title', models.CharField(blank=True, help_text='Second signature title', max_length=100)),
                ('signature_2_name', models.CharField(blank=True, help_text='Second signature name', max_length=100)),
                ('signature_2_image', models.ImageField(blank=True, help_text='Second signature image', null=True, upload_to='certificate_signatures/')),
                ('is_active', models.BooleanField(default=True, help_text='Is this template active?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Certificate Template',
                'verbose_name_plural': 'Certificate Templates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique certificate identifier', unique=True)),
                ('certificate_number', models.CharField(editable=False, help_text='Human-readable certificate number', max_length=50, unique=True)),
                ('certificate_type', models.CharField(choices=[('completion', 'Course Completion'), ('achievement', 'Achievement'), ('participation', 'Participation')], default='completion', help_text='Type of certificate', max_length=20)),
                ('title', models.CharField(help_text='Certificate title', max_length=300)),
                ('completion_percentage', models.DecimalField(decimal_places=2, default=100.0, help_text='Course completion percentage', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('grade', models.CharField(blank=True, help_text='Grade earned (A+, A, B+, etc.)', max_length=10)),
                ('score', models.DecimalField(blank=True, decimal_places=2, help_text='Final score/percentage', max_digits=5, null=True)),
                ('certificate_file', models.FileField(blank=True, help_text='Generated certificate file (PDF/HTML)', null=True, upload_to='certificates/')),
                ('certificate_url', models.URLField(blank=True, help_text='Public URL for certificate verification')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('issued', 'Issued'), ('revoked', 'Revoked')], default='pending', help_text='Certificate status', max_length=20)),
                ('issued_at', models.DateTimeField(blank=True, help_text='Date when certificate was issued', null=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Certificate expiration date (optional)', null=True)),
                ('additional_notes', models.TextField(blank=True, help_text='Additional notes or comments')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(help_text='Course for which certificate was issued', on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='courses.course')),
                ('student', models.ForeignKey(help_text='Student who earned the certificate', on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(blank=True, help_text='Certificate template used', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates', to='certificates.certificatetemplate')),
            ],
            options={
                'verbose_name': 'Certificate',
                'verbose_name_plural': 'Certificates',
                'ordering': ['-issued_at', '-created_at'],
                'unique_together': {('student', 'course')},
            },
        ),
    ]
