# Generated by Django 5.1.5 on 2026-01-19 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('certificates', '0001_initial'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='course',
            field=models.ForeignKey(help_text='Course for which certificate was issued', on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='courses.course'),
        ),
    ]
