# Generated by Django 5.1.5 on 2025-12-15 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_rename_student_enrollment_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='video',
        ),
        migrations.AddField(
            model_name='lecture',
            name='file_size',
            field=models.BigIntegerField(default=0, help_text='File size in bytes'),
        ),
        migrations.AddField(
            model_name='lecture',
            name='hls_playlist',
            field=models.FileField(blank=True, null=True, upload_to='lecture_videos/hls/'),
        ),
        migrations.AddField(
            model_name='lecture',
            name='original_video',
            field=models.FileField(blank=True, null=True, upload_to='lecture_videos/original/'),
        ),
        migrations.AddField(
            model_name='lecture',
            name='processing_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='lecture',
            name='video_1080p',
            field=models.FileField(blank=True, null=True, upload_to='lecture_videos/1080p/'),
        ),
        migrations.AddField(
            model_name='lecture',
            name='video_360p',
            field=models.FileField(blank=True, null=True, upload_to='lecture_videos/360p/'),
        ),
        migrations.AddField(
            model_name='lecture',
            name='video_480p',
            field=models.FileField(blank=True, null=True, upload_to='lecture_videos/480p/'),
        ),
        migrations.AddField(
            model_name='lecture',
            name='video_720p',
            field=models.FileField(blank=True, null=True, upload_to='lecture_videos/720p/'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='duration',
            field=models.PositiveIntegerField(default=0, help_text='Duration in seconds'),
        ),
    ]
