# Generated by Django 5.1.5 on 2025-12-16 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_remove_lecture_video_lecture_file_size_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='original_video',
        ),
        migrations.AddField(
            model_name='lecture',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='lecture_videos/'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='processing_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('direct', 'Direct MP4')], default='pending', max_length=20),
        ),
    ]
