# Generated by Django 5.2 on 2025-05-10 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0002_remove_cart_courses_alter_cart_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='original_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
