# Generated by Django 5.1.5 on 2025-12-15 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0009_alter_cartitem_options_remove_cart_coupon_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='coupon_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='coupon_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
